---

- name: Include server firewall to check
  include_vars: server.yml

- name: Get hostname
  win_shell: echo {{ ansible_hostname }}  >  C:\Windows\Temp\{{ ansible_hostname }}_data.txt
  
- name: Put blank
  block:
    - win_shell: echo test >  C:\Windows\Temp\temp1.txt
    - win_shell: echo test >>  C:\Windows\Temp\temp1.txt
    - win_shell: |
         Get-Content C:\Windows\Temp\temp1.txt | Set-Content C:\Windows\Temp\{{ ansible_hostname }}_data.txt
    
- name: Grab ip only ***** 
  block:
    - win_shell: ipconfig | find "IPv4 Address" >  C:\Windows\Temp\ip.txt
    - win_shell: |
         Get-Content C:\Windows\Temp\ip.txt | %{ $_.Split(':')[1]; } > C:\Windows\Temp\lines.txt
    - win_shell: |
         Get-Content C:\Windows\Temp\lines.txt -First 1 > C:\Windows\Temp\iptop.txt
    - win_shell: |
         (Get-Content C:\Windows\Temp\iptop.txt).Trim() > C:\Windows\Temp\temp2.txt
    - win_shell: |
         Get-Content C:\Windows\Temp\temp2.txt | Set-Content C:\Windows\Temp\{{ ansible_hostname }}_data.txt
                  
- name: Get the cpu core *****
  block:
    - win_shell: |
         Get-WmiObject –class Win32_processor | ft NumberOfCores > C:\Windows\Temp\cpucore.txt
    - win_shell: |
         (Get-Content C:\Windows\Temp\cpucore.txt)[3].Trim() > C:\Windows\Temp\temp3.txt    
    - win_shell: |
         Get-Content C:\Windows\Temp\temp3.txt | Set-Content C:\Windows\Temp\{{ ansible_hostname }}_data.txt

- name: Get the total memory
  block:
    - win_shell: |
         ((Get-WmiObject -class "cim_physicalmemory" | Measure-Object -Property Capacity -Sum).Sum) /1024/1024/1024 > C:\Windows\Temp\temp4.txt    
    - win_shell: |
         Get-Content C:\Windows\Temp\temp4.txt | Set-Content C:\Windows\Temp\{{ ansible_hostname }}_data.txt

- name: Get the total disk ****
  block:
    - win_shell: Get-Disk | Foreach-Object {$_.Size/1024/1024/1024} 
    - win_shell: $b=|Foreach {$a += $_}    
    - win_shell: $b > C:\Windows\Temp\temp5.txt       
    - win_shell: |
         Get-Content C:\Windows\Temp\temp5.txt | Set-Content C:\Windows\Temp\{{ ansible_hostname }}_data.txt

- name: delete csv
  win_shell: del /f /q C:\Windows\Temp\{{ ansible_hostname }}_output.csv
  args:
    executable: cmd
    warn: false
  ignore_errors: True

- name: Put the headers
  win_shell: echo 'Hostname,Check-Host,Port,IPAddress,CPUCore,RAM,Disk' > C:\Windows\Temp\{{ ansible_hostname }}_output.csv
  
- name: Put it in CSV in one line
  block: 
    - win_shell: Clear-Variable c
    - win_shell: Clear-Variable d
    - win_shell: $c=Get-Content -Path /tmp/{{ ansible_hostname }}_data.txt
    - win_shell: $c | %{$v += ($(if($v){", "}) + $_ + $t)}
    - win_shell: $v >> C:\Windows\Temp\{{ ansible_hostname }}_output.csv

- name: Check if remote host port
  wait_for: host={{ item.server2 }} port={{ item.port }} timeout=1
  ignore_errors: True
  register: out
  when: item.server1 == ansible_hostname
  with_items: "{{ servers }}"
  
- debug: var=out  
  
- name: Save remote port   
  win_shell: printf "\n,{{ item.item.server2 }} port {{ item.item.port }} is {% if item.failed %}closed{% else %}open{% endif %}"  >> C:\Windows\Temp\{{ ansible_hostname }}_output.csv
  args:
    executable: cmd
  when: item.item.server1 == ansible_hostname
  with_items: "{{ out.results }}"
  
- name: delete local /tmp/fetched
  win_shell: rm -fr /tmp/fetched/ 
  args:
    executable: cmd
    warn: False
  ignore_errors: True
  delegate_to: localhost
    
- name: Fetching file
  fetch:
    src: C:\Windows\Temp\{{ ansible_hostname }}_output.csv
    dest: /tmp/fetched
    flat: yes

#- name: Combined to one file
#  win_shell: cat /tmp/fetched/{{ ansible_hostname }}/tmp/{{ ansible_hostname }}_output.csv >> /tmp/fetched/main_output.csv && printf '\r\n' >> /tmp/fetched/main_output.csv
#  args:
#    executable: cmd
#  delegate_to: localhost   


 
    
