---

- hosts: all
  gather_facts: false
  become_method: runas
  
  vars:  
    server: vm1
    port: 22
    
    #servers:
      #- server1: win2012r2
      #  server2: vm1
      #  port: 22
        
#PortQry.exe /n {{ servers.server2 }} /p tcp /e {{ item.port }}      

  tasks:
    - name: Check if remote host port
      win_shell: |
         PortQry.exe /n {{ server }} /p tcp /e 22            
      register: out
      ignore_errors: True
      #when: item.server1 == ansible_hostname
      #with_items: "{{ servers }}"
  
    - debug: var=out  
