---

- hosts: all
  gather_facts: false
  become_method: runas

  tasks:
    - name: Check if remote host port
      win_shell: |
         telnet 127.0.0.1 25
      register: out
      ignore_errors: True
      
#- debug: var=out  
