---

- hosts: all
  gather_facts: true
  become_method: runas
  
  vars:  
    servers:
      - server1: win2012r2
        server2: vm1
        port: 22
        
#PortQry.exe /n {{ servers.server2 }} /p tcp /e {{ item.port }}      
#PortQry.exe /n {{ server1 }} /p tcp /e {{ port1 }}           

  tasks:
    - name: Check if remote host port
      win_shell: PortQry.exe /n {{ item.server2 }} /p tcp /e {{ item.port }}
      args:
        executable: cmd           
      register: out        
      when: item.server1|upper == ansible_hostname
      with_items: "{{ servers }}"
  
   #ignore_errors: True
    - debug: var=out  
