---

- hosts: all
  gather_facts: true
  become_method: runas
  
  vars:  
  
    servers:
      - server1: sdcgisazapmdw04
        server2: sdcgisazapmdw09
        port: 22

  tasks:
    - name: Obtain information about a file
      win_stat:
        path: C:\Windows\temp\PortQry.exe
      register: file_info
      
    - name: Copy a single file
      win_copy:
        src: PortQry.exe
        dest: C:\Windows\temp\PortQry.exe
      when: file_info|failed
