---

- hosts: all
  gather_facts: true
  become_method: runas
  
  vars:  
  
    servers:
      - server1: win2012r2
        server2: vm1
        port: 22

  tasks:
    - name: Check if remote host port
      win_shell: |
         PortQry.exe -wt 2 /n {{ item.server2 }} /p tcp /e {{ item.port }}
      register: out   
      ignore_errors: True
      when: item.server1 == ansible_hostname
      with_items: "{{ servers }}"
  
    - debug: var=out  

    - name: Save remote port   
      win_shell: echo  {{ item.stdout }} port {{ item.item.stdout }} is {% if item.failed %}closed or{% else %} open{% endif %} {{ item.stdout }}  >> C:\Windows\Temp\data222.txt
      args:
        executable: cmd
      when: item.item.server1 == ansible_hostname
      with_items: "{{ out.results }}"
