---

- hosts: all
  gather_facts: true
  become_method: runas
  
  vars:  
  
    servers:
      - server1: win2012r2
        server2: vm1
        port: 22

  tasks:
    - name: Check if remote host port
      win_shell: |
         PortQry.exe -wt 2 /n {{ item.server2 }} /p tcp /e {{ item.port }}
      register: out   
      ignore_errors: True
      when: item.server1|upper == ansible_hostname
      with_items: "{{ servers }}"
  
    - debug: var=out  
