---

- hosts: all
  gather_facts: true
  become_method: runas
  
  vars:  
  
    servers:
      - server1: sdcgisazapmdw04
        server2: sdcgisazapmdw09
        port: 22

  tasks:
    - name: Fetching file
      fetch:
        src: C:\Windows\Temp\{{ ansible_hostname }}_output.csv
        dest: /tmp/{{ ansible_hostname }}_output.csv
        #flat: yes
