---

- hosts: all
  gather_facts: false
  become_method: runas

  tasks:
    - name: Check if remote host port
      win_shell: |
         c:\windows\temp\PortQry.exe /n 10.193.177.220 /p tcp /e 25
      register: out
      ignore_errors: True
      
    - debug: var=out  
