---

- hosts: winserv1
  #become: true
  become_method: runas

  vars:
    servers:
      - server1: winserv1
        server2: centos1
        port: 80
    wintemp: C:\Windows\Temp\

  tasks:
    - name: Check if remote host port
      win_shell: ipconfig | find "IPv4 Address" > C:\Windows\Temp\{{ ansible_hostname }}_dos.txt
      args:
        executable: cmd

    #- name: save path
    #  win_shell: cd
    #  args:
    #    executable: cmd
    #  register: out

    #- debug: var=out

    - name: Fetching file
      fetch:
        src: C:\Windows\Temp\{{ ansible_hostname }}_dos.txt
        dest: /tmp/{{ ansible_hostname }}_dos.txt
        flat: yes
      delegate_to: winserv1
    
    #- name: test it
    #  shell: echo {{ out.stdout_lines }} > /tmp/1.txt
      #warn: False
      #ignore_errors: True
    #  delegate_to: localhost
      #with_items: "{{ out.results }}"
