---

- hosts: all
  gather_facts: true
  become_method: runas
  
  vars:  
  
    servers:
      - server1: sdcgisazapmdw04
        server2: sdcgisazapmdw09
        port: 22

  tasks:
    - name: Obtain information about a file
      win_stat:
        path: C:\Windows\system32\PortQry.exe
      register: file_info
      
    - debug: var=file_info
