---

- hosts: all
  gather_facts: false
  become_method: runas

  tasks:
    - name: Check if remote host port
      telnet: 
        host: 10.193.177.220 
        port: 22 
        timeout: 2
        command: 
          - "[quit|exit]"
      
