---

- hosts: all
  become_method: runas

  tasks:
    - name: Put it in CSV in one line
      block: 
        - win_shell: |
            Get-Content -Path C:\Windows\Temp\data5.txt | %{$v += ($(if($v){", "}) + $_ + $t)} ; $v >> C:\Windows\Temp\{{ ansible_hostname }}_output.csv
