---

- hosts: all
  gather_facts: false
  become_method: runas
  
  vars:  
    serverlist:
      - server1: win2012r2
        server2: vm1
        port: 22
        
#PortQry.exe /n {{ servers.server2 }} /p tcp /e {{ item.port }}      
#PortQry.exe /n {{ server1 }} /p tcp /e {{ port1 }}           

  tasks:
    - name: Check if remote host port
      win_shell: PortQry.exe /n vm1 /p tcp /e 22
      args:
        executable: cmd           
      #when: item.server1 == ansible_hostname
      #with_items: "{{ serverlist }}"
  
   #ignore_errors: True
  #register: out
 #   - debug: var=out  
